### ISSUE TITLE
[AzureAD Bug] AzureAD role and account issues

### ISSUE THREAD

**Issue by Sakura-pgh** [yasudacloud/strapi-plugin-sso#20] opened 2023-08-17 03:01 UTC
Thank you very much for the plugin, but I am experiencing the following problem with the integration using AAD！

1. Default role setting at first login set in Single Sign On page for AAD is not working, no matter how to set it, the created role is empty.
2. when using AAD to login, when the mailbox already exists in User, it still creates an account with a duplicate mailbox, especially when this account has been manually given role privileges, the next login will become the same account except for the role.

![image](https://github.com/yasudacloud/strapi-plugin-sso/assets/37110907/eb1aaae3-787f-4805-9472-ee08ef82b6a2)

Thanks！

**Comment by yasudacloud** [comment] 2023-08-17 03:47
@Sakura-pgh 
Thanks for getting back to me.

> Default role setting at first login set in Single Sign On page for AAD is not working, no matter how to set it, the created role is empty.

Please give us a few minutes as we investigate this matter.

> when using AAD to login, when the mailbox already exists in User, it still creates an account with a duplicate mailbox, especially when this account has been manually given role privileges, the next login will become the same account except for the role.

The expected result should be that any Azure or Google login should be unique by email address.
I will get back to you when I find the cause🙏

**Comment by Sakura-pgh** [comment] 2023-08-17 07:49
@yasudacloud Thanks for the quick reply！

I found out something about the mailbox account, the problem is due to the case of the mailbox, for example, for mailboxes 'Sakura' and 'sakura' are the same, but for the database is different, so I suggest that for mailboxes, the creation and lookup are done in lower case!

**Comment by Sakura-pgh** [comment] 2023-08-17 09:13
@yasudacloud About roles should be

services/role.js
```
async azureAdRoles() {
    return await strapi.query('plugin::strapi-plugin-sso.roles').findOne({
      where: {
        oauth_type: this.SSO_TYPE_AZUREAD
      },
    });
  },
```

**Comment by yasudacloud** [comment] 2023-08-17 09:30
@Sakura-pgh 
We may have found the cause.
The fineOne is incorrectly specified and correctly looks like this

```
return await strapi.query('plugin::strapi-plugin-sso.roles').findOne({
  where: {
    oauth_type: this.SSO_TYPE_AZUREAD
  },
});
```

Currently, the condition is not specified correctly, so it seems that the Role is not retrieved even if it is set in the admin screen.

**Comment by yasudacloud** [comment] 2023-08-17 09:31
Oh, sorry.
You wrote the correct code. I did not notice.

**Comment by yasudacloud** [comment] 2023-08-17 14:53
@Sakura-pgh
Version 0.3.0 is now available.
If you don't mind, could you try it again?

**Comment by Sakura-pgh** [comment] 2023-08-18 02:12
@yasudacloud Thanks！
But the issue about email has not yet been resolved, as I mentioned above, and I hope you'll address it sometime as well.



> @yasudacloud Thanks for the quick reply！
> 
> I found out something about the mailbox account, the problem is due to the case of the mailbox, for example, for mailboxes 'Sakura' and 'sakura' are the same, but for the database is different, so I suggest that for mailboxes, the creation and lookup are done in lower case!

**Comment by yasudacloud** [comment] 2023-08-18 02:34
@Sakura-pgh 
Oops, my bad.
I'll try to investigate again.

**Comment by yasudacloud** [comment] 2023-08-18 13:53
@Sakura-pgh 
Hi!
I would like some more information on this issue.
I'm trying to make OAuth users as similar as possible to regular Admin users.

In other words, I'm thinking that this is the correct way to do it, since we distinguish between lower and upper case email addresses when registering users from the admin screen.
On the other hand, if there are any inconveniences I'm not anticipating, I'd like to accommodate them as best I can.

**Comment by Sakura-pgh** [comment] 2023-08-21 02:12
@yasudacloud Hi
If it's based on the default behaviour of user, I think I'm right in saying that it will make email all lowercase when creating and editing User messages.
![image](https://github.com/yasudacloud/strapi-plugin-sso/assets/37110907/085464a3-4825-4b7d-bcf6-a45b5e190c72)

![image](https://github.com/yasudacloud/strapi-plugin-sso/assets/37110907/745f1694-08fb-425c-b438-ed9e172efbd6)

![image](https://github.com/yasudacloud/strapi-plugin-sso/assets/37110907/f30d1029-c49e-4761-a4ad-e0276aefb457)

I type DdEE@163.com, but I get "ddee@163.com"

**Comment by yasudacloud** [comment] 2023-08-24 06:03
@Sakura-pgh 
Sorry for the late reply.
I understand the issue you are pointing out.
However, I believe this needs to be taken into account since the existing spec already distinguishes between upper and lower case letters.
It will take some more time to address this.

**Comment by yasudacloud** [comment] 2023-08-27 12:13
@Sakura-pgh 
Hi!
I've created a PR addressing the uppercase registration issue.
I'll test it further, and if everything looks OK, I'll merge it.

https://github.com/yasudacloud/strapi-plugin-sso/pull/22

**Comment by Sakura-pgh** [comment] 2023-08-29 09:14
@yasudacloud 
Looking forward to your new release!

**Comment by yasudacloud** [comment] 2023-08-29 09:19
@Sakura-pgh 
I published the aforementioned response yesterday as part of Version 0.3.1.
I apologize for the delay in reporting this.

**Comment by yasudacloud** [comment] 2023-09-05 05:23
The fix for this Issue is complete, so I'm closing it.

**Closed by yasudacloud** 2023-09-05 05:23 UTC
